### ISSUE TITLE
[NV-GO-4] API 🚀: Integrations CRUD

### ISSUE THREAD

**Issue by prajjwaldimri** [novuhq/go-novu#11]
🔖 Feature description

Should be able to get, create, update and delete integrations.

🎤 API Reference
https://docs.novu.co/api/get-integrations/
https://docs.novu.co/api/create-integration/
https://docs.novu.co/api/get-active-integrations/
https://docs.novu.co/api/update-integration/
https://docs.novu.co/api/delete-integration/

**Comment by akhill10** [comment]
Hey, can I work on this?

**Comment by samsoft00** [comment]
Sure.

**Comment by prajjwaldimri** [comment]
Hey @akhill10. Just wanted to know how far along are you on this one, as this feature is a blocker for us at Argonaut for a feature that we are developing currently. Let me know if we can collaborate on this, or if I can take it over from you. Thanks

**Comment by akhill10** [comment]
Hey @prajjwaldimri,  completed 50% of it. PR should be up in a day or so. If I get stuck in between, will ask for your help.
