### ISSUE TITLE
[NV-GO-6] API 🚀: Subscriber Notification Feed

### ISSUE THREAD

**Issue by prajjwaldimri** [novuhq/go-novu#14]
🔖 Feature description

Should be able to get notification feed of a subscriber, get count of unseen notifications and mark subscriber feed message as seen.

🎤 API Reference
https://docs.novu.co/api/get-a-notification-feed-for-a-particular-subscriber/
https://docs.novu.co/api/get-the-unseen-notification-count-for-subscribers-feed/
https://docs.novu.co/api/mark-a-subscriber-feed-message-as-seen/

**Comment by prajjwaldimri** [comment]
Will be taking this up as well.

**Comment by samsoft00** [comment]
AWesome @prajjwaldimri are you done with previous issues? if done, please push for review before proceeding. Thank you.

**Comment by prajjwaldimri** [comment]
Yeah. Working on #12 and #13 at the moment.
