### ISSUE TITLE
[NV-GO-3] API 🚀: Add Tenants API feature

### ISSUE THREAD

**Issue by unicodeveloper** [novuhq/go-novu#30]
The tenants feature just became available this week in v0.19 on the UI and API.

This SDK needs to be updated to have this feature.

API reference: https://docs.novu.co/api-reference/tenants/

**Comment by mahendraHegde** [comment]
@unicodeveloper  i can work on this

**Comment by unicodeveloper** [comment]
@mahendraHegde Assigned to you now

**Comment by partik03** [comment]
@unicodeveloper Can I take up this one?

**Comment by partik03** [comment]
@unicodeveloper I have added the pr for this one 
Kindly review it
