### ISSUE TITLE
Incomplete Subscriber Data Update

### ISSUE THREAD

**Issue by KaptinLin** [novuhq/go-novu#34]
### Description

When updating a user's `Name`, I also attempt to update the corresponding `novu` subscriber. For example, if I change the user's `Name` value from `foo1` to `bar1`, I expect the `novu` subscriber's `Name` and `LastName` to be updated accordingly.

However, only the `name` in the `data` field of the subscriber gets updated successfully. The `LastName` remains the same as it was when the subscriber was created.

### Steps To Reproduce

1. Update a user's `Name` value from `foo1` to `bar1`.
2. Use the following code to update the `novu` subscriber:

```go
ctx := context.Background()
subscriberID := *user.ID
subscriber := novu.SubscriberPayload{
    Email:    *user.Email,
    Avatar:   *user.Avatar,
    LastName: *user.Name,
    Data: map[string]interface{}{
        "username":       *user.Username,
        "name":           *user.Name
    },
}
_, err := notifier.SubscriberApi.Update(ctx, subscriberID, subscriber)
```

### Expected behavior

The `LastName` of the `novu` subscriber should be updated to the new `user.Name` value (`bar1`).

### Actual behavior

The `LastName` remains unchanged, while the `name` in the `Data` field gets updated successfully.

### Environment

- Novu version: v0.19.0
- go-novu version: v0.1.2

### Additional context

As seen in the code, I am setting the `LastName` field of the `novu.SubscriberPayload` object to the updated `user.Name` value. However, after the update operation, the `LastName` remains unchanged, while the `name` in the `Data` field gets updated successfully.

### Screenshot
![image](https://github.com/novuhq/go-novu/assets/999331/1ecb58ab-f12a-4939-aba0-ebc08c0a3b75)

**Comment by KaptinLin** [comment]
I would like to add that when I attempt to change the email from `foo1@gmail.com` to `bar1@gmail.com`, the update is successful. It seems that the issue is specifically with the `LastName` field. This additional test indicates that the update functionality works correctly for the `Email` field but not for the `LastName` field. Please consider this information while investigating the issue. Thank you.


![image](https://github.com/novuhq/go-novu/assets/999331/7b2b1c1d-3d12-4276-8a33-21ee75d578f4)

**Comment by Sweetdevil144** [comment]
Hello @KaptinLin,
I am reaching out to inquire about the current status of the mentioned issue. Is it still available for contribution? I appreciate your guidance on this matter.

**Comment by KaptinLin** [comment]
it's fixed in the new version.

**Comment by KaptinLin** [comment]
it's fixed
