### ISSUE TITLE
Add Missing Methods for Execution details

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/go-novu#48]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Execution details

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

**Comment by partik03** [comment]
@Cliftonz can I take up this one?

**Comment by Cliftonz** [comment]
@partik03 Yes, if there are methods to add. If not then I can happily assign you to another issue.

**Comment by partik03** [comment]
@Cliftonz  I can't find any execution api endpoints that aren't included already.So I think this issue should be closed as it is completed.
