### ISSUE TITLE
Add Missing Methods for Blueprints

### ISSUE THREAD

**Issue by Cliftonz** [novuhq/go-novu#51]
Some endpoints of the following section can't be hit from this SDK. 

We would like to ensure that all endpoints can be hit. For this issue, we would like to build out the Blueprints

Some of these methods may already exist.  If so no need to change/update them, just point out that they already exist and we will close the issue.  This is just to bring every SDK we have on par with all the methods available.

Check all the endpoints [here](https://api.novu.co/api#/Workflow%20groups/NotificationGroupsController_updateNotificationGroup) and add the missing ones.

**Comment by Cliftonz** [comment]
@Bezaeel  Assigned feel free to start working on this

**Comment by Bezaeel** [comment]
@Cliftonz thank you, gone ahead to raise a PR

**Comment by Cliftonz** [comment]
@Bezaeel Can you link the PR?

**Comment by Bezaeel** [comment]
@Cliftonz done

**Comment by Bezaeel** [comment]
@Cliftonz still waiting for your review, in mean time, can I pick up others?

**Comment by Cliftonz** [comment]
@Bezaeel Just at me on any other issue that does not have all of the endpoints done and we can go from there.
